/*---------------------------------------------------------------------------------------------
| $Copyright: (c =  2017 Bentley Systems, Incorporated. All rights reserved. $
 *--------------------------------------------------------------------------------------------*/

enum ToolString {
  VIEWINGTOOL_SelectView = "Select view",
  VIEWINGTOOL_WindowArea = "Click and drag to zoom into area defined by the rectangle.",
  VIEWINGTOOL_Rotate = "Click and drag to move view around rotation point. Change rotation point by moving crosshair.",
  VIEWINGTOOL_RotateDrag = "Click and drag to move view around rotation point.",
  VIEWINGTOOL_Look = "Click and drag to look around.",
  VIEWINGTOOL_Pan = "Click and drag to pan view.",
  VIEWINGTOOL_Navigate = "Click and drag to navigate view. Hold Shift to change elevation. Hold Ctrl to look around.",
  VIEWINGTOOL_Scroll = "Click to start scrolling view.",
  VIEWINGTOOL_Zoom = "Click to zoom view.",
  VIEWINGTOOL_SelectViewToFit = "Select view to fit",
  VIEWUNDO_NoPreviousViewOps = "No previous viewing operations",
  VIEWUNDO_NoPreviousUndos = "Only valid after 'View Previous'",
  ELEMENTSETTOOL_PROMPT_IdentifyElement = "Identify element",
  ELEMENTSETTOOL_PROMPT_AcceptSelection = "Accept/Reject Selection",
  ELEMENTSETTOOL_PROMPT_AcceptFence = "Accept/Reject Fence Contents",
  ELEMENTSETTOOL_ERROR_NoFence = "No fence defined",
  ELEMENTSETTOOL_ERROR_NoFenceElems = "No elements in fence",
  ELEMENTSETTOOL_ERROR_NoFenceElemsOutside = "No elements outside fence",
  ELEMENTSETTOOL_ERROR_NoSSElems = "No elements selected.",
  ELEMENTSETTOOL_ERROR_NotSuportedElmType = "Element type not valid for this tool",
  ELEMENTSETTOOL_ERROR_ProjectExtents = "Invalid location. All elements must fit within the volume defined by the project extents.",
  MANIPULATOR_ModifyHandle = "Handle: %s",
  MANIPULATOR_ModifyHandleAngle = "(SHIFT - Tap to change action = ",
  MANIPULATOR_ModifyHandleAction = "(SHIFT - Tap for preserve angle on/off = ",
  MANIPULATOR_ProjectExtents = "Project Extents",
  MANIPULATOR_ModifyProjectExtents = "Modify Project Extents",
  ELEMENTUNDO_NothingToUndo = "No actions to UNDO",
  ELEMENTUNDO_NothingToRedo = "Nothing has been UNDONE",
  ELEMENTUNDO_UndoAll = "Do you really want to UNDO ALL CHANGES?",
  ACCUDRAW_PROMPT_DefineOrigin = "Define X axis origin.",
  ACCUDRAW_PROMPT_DefineXAxis = "Define X axis.",
  ACCUDRAW_PROMPT_DefineYDir = "Define Y axis.",
  ACCUDRAW_PROMPT_DefineElem = "Select element to define rotation.",
  ELEMENTLOCATE_NoElementsFound = "No Elements Found",
  ELEMENTLOCATE_MSG_2 = "Element is in a model with locate turned off",
  ELEMENTLOCATE_MSG_3 = "Level lock is on, and element is not on the active level",
  ELEMENTLOCATE_MSG_4 = "Element is locked",
  ELEMENTLOCATE_MSG_5 = "Element is on a locked level",
  ELEMENTLOCATE_MSG_6 = "Element is view only",
  ELEMENTLOCATE_MSG_7 = "Element not valid for tool",
  ELEMENTLOCATE_MSG_8 = "Element rejected by tool",
  ELEMENTLOCATE_MSG_9 = "Element type not valid for this tool",
  ELEMENTLOCATE_MSG_10 = "Element properties not valid for this tool",
  ELEMENTLOCATE_MSG_11 = "Element is a transient element",
  ELEMENTLOCATE_MSG_12 = "Element is in a model that is not allowed by this tool",
  ELEMENTLOCATE_MSG_13 = "",
  ELEMENTLOCATE_MSG_14 = "",
  ELEMENTLOCATE_MSG_15 = "Element is not snappable",
  ELEMENTLOCATE_MSG_16 = "Element is in a non-snappable model",
  ELEMENTLOCATE_MSG_17 = "",
  ELEMENTLOCATE_MSG_18 = "Element is in a model without Export permission",
  ELEMENTLOCATE_MSG_19 = "",
  ELEMENTLOCATE_MSG_20 = "",
  ELEMENTLOCATE_MSG_21 = "",
  ELEMENTLOCATE_MSG_22 = "Element does not allow this operation",
  ELEMENTLOCATE_MSG_23 = "",
  ELEMENTLOCATE_MSG_24 = "",
  REGIONTOOL_ERROR_NoArea = "Difference results in zero area region",
  REGIONTOOL_ERROR_NoIntersection = "Regions do not intersect",
  REGIONTOOL_ERROR_Unbounded = "Unbounded solution",
  REGIONTOOL_ERROR_NonCoplanar = "Regions are not coplanar",
  REGIONTOOL_ERROR_NoEnclosingArea = "No enclosing region found",
  REGIONTOOL_ERROR_NotClosed = "Element is not closed, can't be used",
  REGIONTOOL_PROMPT_SubtractFrom = "Identify Solid Element",
  REGIONTOOL_PROMPT_Intersection = "Identify Intersecting Elements",
  REGIONTOOL_PROMPT_Union = "Identify Union Elements",
  REGIONTOOL_PROMPT_Difference = "Identify Difference Elements",
  REGIONTOOL_PROMPT_PointEnter = "Enter point",
  REGIONTOOL_PROMPT_PointEnterInside = "Enter point inside area",
  REGIONTOOL_PROMPT_PointReset = "Enter point or RESET to complete",
  REGIONTOOL_PROMPT_AcceptConstruction = "Accept - Complete Operation",
  REGIONTOOL_PROMPT_AcceptRejectMulti = "Accept/Reject (Ctrl+Data to select = ",
}
