/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/

import { expect } from "chai";
import { TechniqueFlags } from "../../../render/webgl/TechniqueFlags";

const descriptions = [
  "Opaque",
  "Opaque-Animated",
  "Opaque-Animated-Shadowable",
  "Opaque-Hilite-Classified",
  "Opaque-Hilite-Overrides",
  "Opaque-Instanced",
  "Opaque-Instanced-Animated",
  "Opaque-Instanced-Animated-Shadowable",
  "Opaque-Instanced-Hilite-Overrides",
  "Opaque-Instanced-Shadowable",
  "Opaque-Shadowable",
  "Translucent",
  "Translucent-Animated",
  "Translucent-Animated-Overrides",
  "Translucent-Animated-Pick",
  "Translucent-Animated-Shadowable",
  "Translucent-Animated-Shadowable-Overrides",
  "Translucent-Animated-Shadowable-Pick",
  "Translucent-Instanced",
  "Translucent-Instanced-Animated",
  "Translucent-Instanced-Animated-Overrides",
  "Translucent-Instanced-Animated-Pick",
  "Translucent-Instanced-Animated-Shadowable",
  "Translucent-Instanced-Animated-Shadowable-Overrides",
  "Translucent-Instanced-Animated-Shadowable-Pick",
  "Translucent-Instanced-Overrides",
  "Translucent-Instanced-Pick",
  "Translucent-Instanced-Shadowable",
  "Translucent-Instanced-Shadowable-Overrides",
  "Translucent-Instanced-Shadowable-Pick",
  "Translucent-Overrides",
  "Translucent-Pick",
  "Translucent-Shadowable",
  "Translucent-Shadowable-Overrides",
  "Translucent-Shadowable-Pick",
  "Opaque-Animated-Overrides",
  "Opaque-Animated-Pick",
  "Opaque-Animated-Shadowable-Overrides",
  "Opaque-Animated-Shadowable-Pick",
  "Opaque-Animated-Thematic",
  "Opaque-Animated-Thematic-Overrides",
  "Opaque-Animated-Thematic-Pick",
  "Opaque-Classified",
  "Opaque-Classified-Overrides",
  "Opaque-Classified-Pick",
  "Opaque-Classified-Shadowable",
  "Opaque-Classified-Shadowable-Overrides",
  "Opaque-Classified-Shadowable-Pick",
  "Opaque-Classified-Thematic",
  "Opaque-Classified-Thematic-Overrides",
  "Opaque-Classified-Thematic-Pick",
  "Opaque-EdgeTestNeeded-Animated-Overrides",
  "Opaque-EdgeTestNeeded-Animated-Pick",
  "Opaque-EdgeTestNeeded-Animated-Shadowable-Overrides",
  "Opaque-EdgeTestNeeded-Animated-Shadowable-Pick",
  "Opaque-EdgeTestNeeded-Animated-Thematic-Overrides",
  "Opaque-EdgeTestNeeded-Animated-Thematic-Pick",
  "Opaque-EdgeTestNeeded-Overrides",
  "Opaque-EdgeTestNeeded-Pick",
  "Opaque-EdgeTestNeeded-Shadowable-Overrides",
  "Opaque-EdgeTestNeeded-Shadowable-Pick",
  "Opaque-EdgeTestNeeded-Thematic-Overrides",
  "Opaque-EdgeTestNeeded-Thematic-Pick",
  "Opaque-Instanced-Animated-Overrides",
  "Opaque-Instanced-Animated-Pick",
  "Opaque-Instanced-Animated-Shadowable-Overrides",
  "Opaque-Instanced-Animated-Shadowable-Pick",
  "Opaque-Instanced-Animated-Thematic",
  "Opaque-Instanced-Animated-Thematic-Overrides",
  "Opaque-Instanced-Animated-Thematic-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Shadowable-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Shadowable-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Thematic-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Animated-Thematic-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Shadowable-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Shadowable-Pick",
  "Opaque-Instanced-EdgeTestNeeded-Thematic-Overrides",
  "Opaque-Instanced-EdgeTestNeeded-Thematic-Pick",
  "Opaque-Instanced-Overrides",
  "Opaque-Instanced-Pick",
  "Opaque-Instanced-Shadowable-Overrides",
  "Opaque-Instanced-Shadowable-Pick",
  "Opaque-Instanced-Thematic",
  "Opaque-Instanced-Thematic-Overrides",
  "Opaque-Instanced-Thematic-Pick",
  "Opaque-Overrides",
  "Opaque-Pick",
  "Opaque-Shadowable-Overrides",
  "Opaque-Shadowable-Pick",
  "Opaque-Thematic-Overrides",
  "Opaque-Thematic-Pick",
  "Translucent-Animated-Thematic",
  "Translucent-Animated-Thematic-Overrides",
  "Translucent-Animated-Thematic-Pick",
  "Translucent-Classified",
  "Translucent-Classified-Overrides",
  "Translucent-Classified-Pick",
  "Translucent-Classified-Shadowable",
  "Translucent-Classified-Shadowable-Overrides",
  "Translucent-Classified-Shadowable-Pick",
  "Translucent-Classified-Thematic",
  "Translucent-Classified-Thematic-Overrides",
  "Translucent-Classified-Thematic-Pick",
  "Translucent-EdgeTestNeeded-Animated-Overrides",
  "Translucent-EdgeTestNeeded-Animated-Pick",
  "Translucent-EdgeTestNeeded-Animated-Shadowable-Overrides",
  "Translucent-EdgeTestNeeded-Animated-Shadowable-Pick",
  "Translucent-EdgeTestNeeded-Animated-Thematic-Overrides",
  "Translucent-EdgeTestNeeded-Animated-Thematic-Pick",
  "Translucent-EdgeTestNeeded-Overrides",
  "Translucent-EdgeTestNeeded-Pick",
  "Translucent-EdgeTestNeeded-Shadowable-Overrides",
  "Translucent-EdgeTestNeeded-Shadowable-Pick",
  "Translucent-EdgeTestNeeded-Thematic-Overrides",
  "Translucent-EdgeTestNeeded-Thematic-Pick",
  "Translucent-Instanced-Animated-Thematic",
  "Translucent-Instanced-Animated-Thematic-Overrides",
  "Translucent-Instanced-Animated-Thematic-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Shadowable-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Shadowable-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Thematic-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Animated-Thematic-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Shadowable-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Shadowable-Pick",
  "Translucent-Instanced-EdgeTestNeeded-Thematic-Overrides",
  "Translucent-Instanced-EdgeTestNeeded-Thematic-Pick",
  "Translucent-Instanced-Thematic",
  "Translucent-Instanced-Thematic-Overrides",
  "Translucent-Instanced-Thematic-Pick",
  "Translucent-Thematic",
  "Translucent-Thematic-Overrides",
  "Translucent-Thematic-Pick",
];

describe("TechniqueFlags", () => {
  it("initializes from description", () => {
    for (const description of descriptions) {
      const flags = TechniqueFlags.fromDescription(description);
      expect(flags.buildDescription()).to.equal(description);
    }
  });

  it("compares for equality", () => {
    for (const descA of descriptions) {
      for (const descB of descriptions) {
        const flagsA = TechniqueFlags.fromDescription(descA);
        const flagsB = TechniqueFlags.fromDescription(descB);
        expect(flagsA.equals(flagsB)).to.equal(descA === descB);
      }
    }
  });
});
