# This configuration defines the rules in place for Mergify to follow.
#
# For more details about what each rule means, visit https://docs.mergify.io.

pull_request_rules:

  # - name: Run Azure CI job once ready to merge
  #   conditions:
  #     - "#approved-reviews-by>=1"
  #     - "#changes-requested-reviews-by=0"
  #     - "check-success=license/cla"
  #     - -closed
  #     - -conflict
  #   actions:
  #     comments:
  #       message: /azp run

  - name: update all PRs
    conditions:
      - "#changes-requested-reviews-by=0"
      - -draft
      - base=master
    actions:
      update: {}
