# Configuration file for mergify

# Branch version variables
variables:
  current_minor: &current_minor "release/5.6.x"
  previous_minor: &previous_minor "release/5.4.x"
  previous_major: &previous_major "release/4.11.x"

defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"
      title: "{{ title }} (backport #{{ number }}) [{{ destination_branch }}]"

pull_request_rules:
  - name: Add reviewers to backports
    conditions:
      - and:
          - base~=release\/[0-9]+.[0-9]+.x
          - approved-reviews-by!=@iTwin/itwinjs-core-backport-reviewers
    actions:
      request_reviews:
        teams:
          - "@iTwin/itwinjs-core-backport-reviewers"

  - name: Ask to resolve conflict
    conditions:
      - and:
          - conflict
          - -draft
    actions:
      comment:
        message: |
          This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/

  - name: Automatic backport for Security fixes
    conditions:
      - and:
          - merged
          - base=master
          - label="security"
    actions:
      backport:
        branches:
          - *current_minor
          - *previous_minor
          - *previous_major