# This configuration defines the rules in place for Mergify to follow.
#
# For more details about what each rule means, visit https://docs.mergify.io.

pull_request_rules:

  - name: update all PRs
    conditions:
      - "#changes-requested-reviews-by=0"
      - -draft
      - base~=master|release/*
      - check-success=iModel.js
      - check-success=iModel.js Integration - GitHub
      - check-success=iModelJs Docs
      - check-success=license/cla
    actions:
      update: {}

  # - name: automatic merge of native addon updates
  #   conditions:
  #     - head~=native/*
  #     - base=master
  #     # Mergify requests required status checks so no need to check here
  #   actions:
  #     merge:
  #       method: merge
  #       strict: true
  #       commit_message: "Update @bentley/imodeljs-native"
