# Configuration file for mergify

pull_request_rules:
  - name: Add reviewers to backports
    conditions:
      - base~=release\/[0-9]+.[0-9]+.x
    actions:
      request_reviews:
        teams:
          - "@iTwin/itwinjs-core-backport-reviewers"
