/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/

/* eslint-disable @typescript-eslint/naming-convention */

export class EarthquakeSince1970Dataset {

  public static Earthquakes1970LayerCapabilities: any = {
    currentVersion: 10.91,
    id: 0,
    name: "Earthquakes1970",
    type: "Feature Layer",
    parentLayer: null,
    defaultVisibility: true,
    minScale: 0,
    maxScale: 0,
    canScaleSymbols: false,
    geometryType: "esriGeometryPoint",
    description: "Data represented by this map is not updated on a regular basis.  This is a sample service hosted by ESRI, powered by ArcGIS Server. ESRI reserves the right to change or remove this service at any time and without notice.\n",
    copyrightText: "",
    editFieldsInfo: null,
    ownershipBasedAccessControlForFeatures: null,
    syncCanReturnChanges: false,
    relationships: [],
    isDataVersioned: false,
    isDataArchived: false,
    isCoGoEnabled: false,
    supportsRollbackOnFailureParameter: true,
    archivingInfo: {
      supportsQueryWithHistoricMoment: false,
      startArchivingMoment: -1,
    },
    supportsStatistics: true,
    supportsAdvancedQueries: true,
    supportsValidateSQL: true,
    supportsCoordinatesQuantization: true,
    supportsCalculate: true,
    supportsDatumTransformation: true,
    advancedQueryCapabilities: {
      supportsPagination: true,
      supportsTrueCurve: true,
      supportsQueryWithDistance: true,
      supportsReturningQueryExtent: true,
      supportsStatistics: true,
      supportsHavingClause: true,
      supportsOrderBy: true,
      supportsDistinct: true,
      supportsCountDistinct: true,
      supportsQueryWithResultType: true,
      supportsReturningGeometryCentroid: false,
      supportsSqlExpression: true,
      supportsQueryWithDatumTransformation: true,
    },
    extent: {
      xmin: -179.98399999999998,
      ymin: -62.87699999999998,
      xmax: 179.10000000000008,
      ymax: 70.78000000000003,
      spatialReference: {
        wkid: 4326,
        latestWkid: 4326,
      },
    },
    sourceSpatialReference: {
      wkid: 4326,
      latestWkid: 4326,
    },
    drawingInfo: {
      renderer: {
        type: "classBreaks",
        field: "magnitude",
        classificationMethod: "esriClassifyNaturalBreaks",
        minValue: 1.6,
        classBreakInfos: [
          {
            symbol: {
              type: "esriPMS",
              url: "1a5ce93c9ddd121f21789ff08f50b383",
              imageData: "iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAQ1JREFUOI2d071KA1EQhuF3QzBkJ4XESmwtUouFhaIXIAhqayUEQawkVoLBwh8UsRR7L0Cwt/UevAMJ22RnYAsZC5eFRLM5m6+bYc4z05w6ATGjFcekZTP1aUiaErvzrsqWCDozFEWNM8hWgVPgcibIjCX3rJeXPVWeRPiqDLlzBcR52QIugONKkFl7xT05GGt3zXiMYz6DIffkAYjG5925BvaDIFV2gc0JO/ZU22siyUcpNBgwB9xOuvQ3yR2wUQo1m5wAy+UQ66rsiPD6LzQcsgCcT0HyNG7cs7co4vsPVKvRB+bDoKxjxiHwPAKZ0XHnKAwp0lflRQQtIHfuxy8MyCL51ykeirBdERnJD80TUfp6vTFHAAAAAElFTkSuQmCC",
              contentType: "image/png",
              width: 13,
              height: 11,
              angle: 0,
              xoffset: 0,
              yoffset: 0,
            },
            classMaxValue: 5,
            label: "1.600000 - 5.000000",
            description: "",
          },
          {
            symbol: {
              type: "esriPMS",
              url: "065667453660362eb9259f9b624cb128",
              imageData: "iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAARxJREFUOI2d0z1Lw1AUxvF/QrE06SB1EleHzuLgoOgHEARfNkMGoQjiJHUSLA6+oIijZEtTQXAS3F39Dn4DkSz2Xgwix6E10GjTmz7bOZz7O2e5JQyiH6g6W3TzZkqjkO49jnzyrEJWXB81NmR9lQ8hmcfmADgZC9JtZoSk2S+bKuTW9XkrDInNKYLTL6vYHAN7hSDdqc2JxF6m3dARN47HqzEkEl8DVnZe4AzYNIJUxDqwPGTHhopqC64Xv+RC7wETwMWwS3uJL4GlXKhSYR+YzYdYVB3W3G0e/4U+2kwBRyOQXqR8LkHyZDX4/gPZFi1g0ggiqesKO0AwAOmIusCuGZKmpULuXB+VQgJX2QsNMv37ddKHrsdqQWQgP4w0TSILuEHdAAAAAElFTkSuQmCC",
              contentType: "image/png",
              width: 13,
              height: 11,
              angle: 0,
              xoffset: 0,
              yoffset: 0,
            },
            classMaxValue: 5.9,
            label: "5.000001 - 5.900000",
            description: "",
          },
          {
            symbol: {
              type: "esriPMS",
              url: "68fc02d60d18137f1c9a2bf2e58fdffb",
              imageData: "iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAASJJREFUOI2d079Lw0AYxvFvjtJi0kHqJK4OncXBQdG9QsAYcXESRBBdpE6CxcEfKOIo7o4iB3Z29X9w7CaSxd7BYey5xEKjTZM+2/vy3ud9lyuRI7pB1W3TzZopjUK6Ia6NeVE+K55EjQ05ceUIzDyCQ+B0LEhvMmONaSZlU/nceZL3wpA1nAFuUlYRnAB7hSAd1uZsHG2l2ju6wa3b5i03ZOPoBnDS87bMObCeC1IBa/RYHrIjUH5twZPRayb0cUCZDpfDLgVARFfAUiY00WEfmM2EYFH5+J5E/gt9bjCF4RgxggEQlQuLeXbg+w8kvmghmMzBAKauA7Z55H4A0iF1G7ObD0nSo6V8HjyJ6kM25jp9YY5M/36d/kPvidWCyEB+ACGWUwzkvHSJAAAAAElFTkSuQmCC",
              contentType: "image/png",
              width: 13,
              height: 11,
              angle: 0,
              xoffset: 0,
              yoffset: 0,
            },
            classMaxValue: 6.9,
            label: "5.900001 - 6.900000",
            description: "",
          },
          {
            symbol: {
              type: "esriPMS",
              url: "21b2e5d7cac48771fdbbbd9f804f664f",
              imageData: "iVBORw0KGgoAAAANSUhEUgAAABIAAAAPCAYAAADphp8SAAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAQRJREFUOI2d071KA1EQBtATCQazKWStxNYitVhYKPoAgqC2VoIIYiWxEgwW/qCIpdj7AIK9re/gG4hsY3ZhC7kWhkiiSTb5uhnmnpnmlhVIRq1Ka9BMeRjSohp4SVmLSMeGSpXKsTxfxBHOxoIy5kKeN9plI+U+4n1kKHCOarus4RQHI0FZHC+EJNnpae9l3FV5KwyFJLlFqXc+cIHtQlDKJlb77NhK43gpSpLXgdAHk7jqdylIkmusDISmOMT8QIjllI2Ip3+hT2ZwMgT5SaVyGfL8ucTXH2iCJqYLQXlez9jFQxeUUQ/sF0J+00x5jEg7UOCm98ICmdX+Op2HEesjIl35BslJQhl9PQgOAAAAAElFTkSuQmCC",
              contentType: "image/png",
              width: 13,
              height: 11,
              angle: 0,
              xoffset: 0,
              yoffset: 0,
            },
            classMaxValue: 9,
            label: "6.900001 - 9.000000",
            description: "",
          },
        ],
      },
      transparency: 0,
      labelingInfo: null,
    },
    hasM: false,
    hasZ: false,
    allowGeometryUpdates: true,
    allowTrueCurvesUpdates: false,
    onlyAllowTrueCurveUpdatesByTrueCurveClients: false,
    timeInfo: {
      startTimeField: "Date_",
      endTimeField: null,
      trackIdField: null,
      timeExtent: [
        259200000,
        1243468800000,
      ],
      timeReference: null,
      timeInterval: 1,
      timeIntervalUnits: "esriTimeUnitsYears",
      exportOptions: {
        useTime: true,
        timeDataCumulative: false,
        timeOffset: null,
        timeOffsetUnits: null,
      },
      hasLiveData: true,
    },
    hasAttachments: false,
    supportsApplyEditsWithGlobalIds: false,
    htmlPopupType: "esriServerHTMLPopupTypeNone",
    objectIdField: "objectid",
    globalIdField: "",
    displayField: "name",
    typeIdField: "",
    subtypeField: "",
    fields: [
      {
        name: "objectid",
        type: "esriFieldTypeOID",
        alias: "OBJECTID",
        domain: null,
        editable: false,
        nullable: false,
        defaultValue: null,
        modelName: "OBJECTID",
      },
      {
        name: "year_",
        type: "esriFieldTypeDouble",
        alias: "Year_",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "year_",
      },
      {
        name: "mo",
        type: "esriFieldTypeDouble",
        alias: "Mo",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "mo",
      },
      {
        name: "dy",
        type: "esriFieldTypeDouble",
        alias: "Dy",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "dy",
      },
      {
        name: "hr",
        type: "esriFieldTypeDouble",
        alias: "Hr",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hr",
      },
      {
        name: "mn",
        type: "esriFieldTypeDouble",
        alias: "Mn",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "mn",
      },
      {
        name: "sec",
        type: "esriFieldTypeDouble",
        alias: "Sec",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "sec",
      },
      {
        name: "tsu",
        type: "esriFieldTypeString",
        alias: "Tsu",
        domain: null,
        editable: true,
        nullable: true,
        length: 255,
        defaultValue: null,
        modelName: "tsu",
      },
      {
        name: "name",
        type: "esriFieldTypeString",
        alias: "Name",
        domain: null,
        editable: true,
        nullable: true,
        length: 255,
        defaultValue: null,
        modelName: "name",
      },
      {
        name: "latitude",
        type: "esriFieldTypeDouble",
        alias: "Latitude",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "latitude",
      },
      {
        name: "longitude",
        type: "esriFieldTypeDouble",
        alias: "Longitude",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "longitude",
      },
      {
        name: "focal",
        type: "esriFieldTypeDouble",
        alias: "Focal",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "focal",
      },
      {
        name: "magnitude",
        type: "esriFieldTypeDouble",
        alias: "Magnitude",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "magnitude",
      },
      {
        name: "mmi_int",
        type: "esriFieldTypeDouble",
        alias: "MMI_Int",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "mmi_int",
      },
      {
        name: "num_deaths",
        type: "esriFieldTypeDouble",
        alias: "Num_Deaths",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "num_deaths",
      },
      {
        name: "hist_deaths",
        type: "esriFieldTypeDouble",
        alias: "Hist_Deaths",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hist_deaths",
      },
      {
        name: "num_injured",
        type: "esriFieldTypeDouble",
        alias: "Num_Injured",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "num_injured",
      },
      {
        name: "hist_injured",
        type: "esriFieldTypeDouble",
        alias: "Hist_Injured",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hist_injured",
      },
      {
        name: "mill_damages",
        type: "esriFieldTypeDouble",
        alias: "Mill_Damages",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "mill_damages",
      },
      {
        name: "hist_damage",
        type: "esriFieldTypeDouble",
        alias: "Hist_Damage",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hist_damage",
      },
      {
        name: "num_houses_dest",
        type: "esriFieldTypeDouble",
        alias: "Num_Houses_Dest",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "num_houses_dest",
      },
      {
        name: "hist_houses_dest",
        type: "esriFieldTypeDouble",
        alias: "Hist_Houses_Dest",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hist_houses_dest",
      },
      {
        name: "num_houses_dam",
        type: "esriFieldTypeDouble",
        alias: "Num_Houses_Dam",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "num_houses_dam",
      },
      {
        name: "hist_houses_dam",
        type: "esriFieldTypeDouble",
        alias: "Hist_Houses_Dam",
        domain: null,
        editable: true,
        nullable: true,
        defaultValue: null,
        modelName: "hist_houses_dam",
      },
      {
        name: "date_",
        type: "esriFieldTypeDate",
        alias: "Date_",
        domain: null,
        editable: true,
        nullable: true,
        length: 8,
        defaultValue: null,
        modelName: "date_",
      },
      {
        name: "yyyymmdd",
        type: "esriFieldTypeString",
        alias: "YYYYMMDD",
        domain: null,
        editable: true,
        nullable: true,
        length: 255,
        defaultValue: null,
        modelName: "yyyymmdd",
      },
      {
        name: "yyyymmddhhmm",
        type: "esriFieldTypeString",
        alias: "YYYYMMDDHHMM",
        domain: null,
        editable: true,
        nullable: true,
        length: 255,
        defaultValue: null,
        modelName: "yyyymmddhhmm",
      },
      {
        name: "yyyymmddhhmmss",
        type: "esriFieldTypeString",
        alias: "YYYYMMDDHHMMSS",
        domain: null,
        editable: true,
        nullable: true,
        length: 255,
        defaultValue: null,
        modelName: "yyyymmddhhmmss",
      },
    ],
    geometryField: {
      name: "shape",
      type: "esriFieldTypeGeometry",
      alias: "shape",
      domain: null,
      editable: true,
      nullable: true,
      defaultValue: null,
      modelName: "Shape",
    },
    indexes: [
      {
        name: "r22_sde_rowid_uk",
        fields: "objectid",
        isAscending: true,
        isUnique: true,
        description: "",
      },
      {
        name: "a4_ix1",
        fields: "shape",
        isAscending: true,
        isUnique: true,
        description: "",
      },
    ],
    dateFieldsTimeReference: {
      timeZone: "UTC",
      respectsDaylightSaving: false,
    },
    types: [],
    templates: [
      {
        name: "Earthquakes1970",
        description: "",
        prototype: {
          attributes: {
            yyyymmddhhmm: null,
            yyyymmddhhmmss: null,
            year_: null,
            mo: null,
            dy: null,
            hr: null,
            mn: null,
            sec: null,
            tsu: null,
            name: null,
            latitude: null,
            longitude: null,
            focal: null,
            magnitude: null,
            mmi_int: null,
            num_deaths: null,
            hist_deaths: null,
            num_injured: null,
            hist_injured: null,
            mill_damages: null,
            hist_damage: null,
            num_houses_dest: null,
            hist_houses_dest: null,
            num_houses_dam: null,
            hist_houses_dam: null,
            date_: null,
            yyyymmdd: null,
          },
        },
        drawingTool: "esriFeatureEditToolPoint",
      },
    ],
    maxRecordCount: 1000,
    supportedQueryFormats: "JSON, geoJSON",
    capabilities: "Query",
    useStandardizedQueries: true,
    standardMaxRecordCount: 32000,
    tileMaxRecordCount: 8000,
    standardMaxRecordCountNoGeometry: 32000,
    maxRecordCountFactor: 1,

  };
}
