/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/

export class NewYorkDataset {

  public static serviceCapabilities: any =
  {
    currentVersion : 10.81,
    serviceItemId : "af1ebcf87a9741458b08360b5802a003",
    hasChangeTrackingEnabledViews : true,
    serviceDescription : "Summary text",
    hasVersionedData : false,
    supportsDisconnectedEditing : false,
    hasStaticData : false,
    hasSharedDomains : false,
    maxRecordCount : 1000,
    supportedQueryFormats : "JSON",
    supportsVCSProjection : false,
    supportedExportFormats : "csv,shapefile,sqlite,geoPackage,filegdb,featureCollection,geojson,excel",
    capabilities : "Query,ChangeTracking",
    description : "My Description",
    copyrightText : "",
    spatialReference : {
      wkid : 102100,
      latestWkid : 3857,
    },
    initialExtent : {
      xmin : -8253177.9212990291,
      ymin : 4956654.8286338719,
      xmax : -8218318.9974145154,
      ymax : 4971008.5031745536,
      spatialReference : {
        wkid : 102100,
        latestWkid : 3857,
      },
    },
    fullExtent : {
      xmin : -8270363.8159049358,
      ymin : 4935557.2945022825,
      xmax : -8204174.9423192516,
      ymax : 5000899.6957413526,
      spatialReference : {
        wkid : 102100,
        latestWkid : 3857,
      },
    },
    allowGeometryUpdates : true,
    units : "esriMeters",
    supportsAppend : true,
    supportsSharedDomains : true,
    supportsWebHooks : true,
    supportsTemporalLayers : true,
    layerOverridesEnabled : true,
    size : 132923392,
    syncEnabled : false,
    extractChangesCapabilities : {
      supportsReturnIdsOnly : true,
      supportsReturnExtentOnly : true,
      supportsReturnAttachments : true,
      supportsLayerQueries : true,
      supportsGeometry : true,
      supportsFeatureReturn : true,
      supportsReturnHasGeometryUpdates : false,
      supportsReturnDeletedFeatures : true,
      supportsServerGens : true,
    },
    supportsApplyEditsWithGlobalIds : true,
    supportsReturnDeleteResults : true,
    supportsLayerOverrides : true,
    supportsTilesAndBasicQueriesMode : true,
    supportsQueryContingentValues : true,
    supportedContingentValuesFormats : "JSON, PBF",
    supportsContingentValuesJson : 2,
    advancedEditingCapabilities : {
      supportsSplit : false,
      supportsReturnServiceEditsInSourceSR : false,
      supportsAsyncApplyEdits : true,
      supportsReturnEditResults : true,
    },
    editorTrackingInfo : {
      enableEditorTracking : false,
      enableOwnershipAccessControl : false,
      allowOthersToQuery : true,
      allowOthersToUpdate : true,
      allowOthersToDelete : false,
      allowAnonymousToQuery : true,
      allowAnonymousToUpdate : true,
      allowAnonymousToDelete : true,
    },
    changeTrackingInfo :
    {
      lastSyncDate : 1637077884618,
      layerServerGens : [
        {
          id : 0,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 1,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 2,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 3,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 4,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 5,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 6,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 7,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 8,
          minServerGen : 498989,
          serverGen : 689984,
        },
        {
          id : 9,
          minServerGen : 498989,
          serverGen : 689984,
        },
      ],
    },
    xssPreventionInfo : {
      xssPreventionEnabled : true,
      xssPreventionRule : "InputOnly",
      xssInputRule : "rejectInvalid",
    },
    layers : [
      {
        id : 0,
        name : "Street",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 150000,
        maxScale : 0,
        geometryType : "esriGeometryPolyline",
      },
      {
        id : 1,
        name : "Highway",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 150000,
        maxScale : 0,
        geometryType : "esriGeometryPolyline",
      },
      {
        id : 2,
        name : "Block",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 150000,
        maxScale : 0,
        geometryType : "esriGeometryPolyline",
      },
      {
        id : 3,
        name : "Shoreline",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolyline",
      },
      {
        id : 4,
        name : "nyco",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
      {
        id : 5,
        name : "nylh",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
      {
        id : 6,
        name : "nysp",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
      {
        id : 7,
        name : "nysp_sd",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
      {
        id : 8,
        name : "nyzd",
        parentLayerId : -1,
        defaultVisibility : false,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
      {
        id : 9,
        name : "nyzma",
        parentLayerId : -1,
        defaultVisibility : true,
        subLayerIds : null,
        minScale : 0,
        maxScale : 0,
        geometryType : "esriGeometryPolygon",
      },
    ],
    tables : [],
  };

  public static streetsLayerCapabilities: any = {
    currentVersion:10.81,id:0,name:"Street",type:"Feature Layer",serviceItemId:"af1ebcf87a9741458b08360b5802a003",cacheMaxAge:30,displayField:"borough",description:"",copyrightText:"",defaultVisibility:true,serverGens:{minServerGen:498989,serverGen:689763},
    editingInfo:{lastEditDate:1637077888141},
    relationships:[],isDataVersioned:false,hasContingentValuesDefinition:false,supportsAppend:true,supportsCalculate:true,supportsASyncCalculate:true,supportsTruncate:true,supportsAttachmentsByUploadId:true,supportsAttachmentsResizing:true,supportsRollbackOnFailureParameter:true,supportsStatistics:true,supportsExceedsLimitStatistics:true,supportsAdvancedQueries:true,supportsValidateSql:true,supportsCoordinatesQuantization:true,supportsLayerOverrides:true,supportsTilesAndBasicQueriesMode:true,supportsFieldDescriptionProperty:true,supportsQuantizationEditMode:true,supportsApplyEditsWithGlobalIds:true,supportsMultiScaleGeometry:true,supportsReturningQueryGeometry:true,hasGeometryProperties:true,geometryProperties:{shapeLengthFieldName:"Shape__Length",units:"esriMeters"},
    advancedQueryCapabilities:{supportsPagination:true,supportsQueryAttachmentsCountOnly:true,supportsPaginationOnAggregatedQueries:true,supportsQueryRelatedPagination:true,supportsQueryWithDistance:true,supportsReturningQueryExtent:true,supportsStatistics:true,supportsOrderBy:true,supportsDistinct:true,supportsQueryWithResultType:true,supportsSqlExpression:true,supportsAdvancedQueryRelated:true,supportsCountDistinct:true,supportsPercentileStatistics:true,supportsSpatialAggregationStatistics:true,supportedSpatialAggregationStatistics:["EnvelopeAggregate","CentroidAggregate","ConvexHullAggregate"],supportsLod:true,supportsQueryWithLodSR:false,supportedLodTypes:["geohash"],supportsReturningGeometryCentroid:false,supportsReturningGeometryProperties:true,supportsQueryWithDatumTransformation:true,supportsHavingClause:true,supportsOutFieldSQLExpression:true,supportsMaxRecordCountFactor:true,supportsTopFeaturesQuery:true,supportsDisjointSpatialRel:true,supportsQueryWithCacheHint:true,supportedOperationsWithCacheHint:["query","queryTopFilter","queryAnalytics","queryAttachments","queryRelated"],supportsQueryAnalytic:true,supportsDefaultSR:true,supportsFullTextSearch:true},
    advancedQueryAnalyticCapabilities:{supportsLinearRegression:true,supportsAsync:true,supportsPercentileAnalytic:true},
    advancedEditingCapabilities:{supportedSqlFormatsInCalculate:["standard"],supportsAsyncApplyEdits:true,supportsReturnEditResults:true},
    infoInEstimates:["extent","count"],useStandardizedQueries:true,geometryType:"esriGeometryPolyline",minScale:150000,maxScale:0,extent:{xmin:-8266144.7918439023,ymin:4938569.7715200111,xmax:-8204248.7873679493,ymax:4999630.6406602357,spatialReference:{wkid:102100,latestWkid:3857}},
    drawingInfo:{renderer:{type:"simple",symbol:{type:"esriSLS",style:"esriSLSSolid",color:[153,0,5,255],width:1},
      label:"",description:""},
    transparency:0,labelingInfo:null},
    allowGeometryUpdates:true,
    hasAttachments:false,
    htmlPopupType:"esriServerHTMLPopupTypeAsHTMLText",
    hasM:false,hasZ:false,objectIdField:"OBJECTID",
    uniqueIdField:{name:"OBJECTID",
      isSystemMaintained:true},
    globalIdField:"GlobalID",
    typeIdField:"",
    fields:
    [{name:"borough",type:"esriFieldTypeString",alias:"borough",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"build_stat",type:"esriFieldTypeString",alias:"build_stat",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"cco_st",type:"esriFieldTypeString",alias:"cco_st",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"date_edit_",type:"esriFieldTypeDate",alias:"date_edit_",sqlType:"sqlTypeOther",length:8,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"time_edit_",type:"esriFieldTypeString",alias:"time_edit_",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"feat_statu",type:"esriFieldTypeString",alias:"feat_statu",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"feat_type",type:"esriFieldTypeString",alias:"feat_type",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"honorary_n",type:"esriFieldTypeString",alias:"honorary_n",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"marg_wharf",type:"esriFieldTypeString",alias:"marg_wharf",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"old_st_nm",type:"esriFieldTypeString",alias:"old_st_nm",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"paper_st",type:"esriFieldTypeString",alias:"paper_st",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"record_st",type:"esriFieldTypeString",alias:"record_st",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"roadway_ty",type:"esriFieldTypeString",alias:"roadway_ty",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"route_type",type:"esriFieldTypeString",alias:"route_type",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"stair_st",type:"esriFieldTypeString",alias:"stair_st",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"street_nm",type:"esriFieldTypeString",alias:"street_nm",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"streetwidt",type:"esriFieldTypeString",alias:"streetwidt",sqlType:"sqlTypeOther",length:254,nullable:true,editable:true,domain:null,defaultValue:null},
      {name:"OBJECTID",type:"esriFieldTypeOID",alias:"OBJECTID",sqlType:"sqlTypeOther",nullable:false,editable:false,domain:null,defaultValue:null},
      {name:"Shape__Length",type:"esriFieldTypeDouble",alias:"Shape__Length",sqlType:"sqlTypeDouble",nullable:true,editable:false,domain:null,defaultValue:null},
      {name:"GlobalID",type:"esriFieldTypeGlobalID",alias:"GlobalID",sqlType:"sqlTypeOther",length:38,nullable:false,editable:false,domain:null,defaultValue:"NEWID() WITH VALUES"}],indexes:[{name:"PK__NEWYORK3__F4B70D858AB09618",fields:"OBJECTID",isAscending:true,isUnique:true,description:""},
      {name:"user_70600.NEWYORK3857_STREET_Shape_sidx",fields:"Shape",isAscending:true,isUnique:false,description:""},
      {name:"Shape__Length_Index",fields:"Shape__Length",isAscending:true,isUnique:false,description:""},
      {name:"GlobalID_Index",fields:"GlobalID",isAscending:false,isUnique:true,description:""}],dateFieldsTimeReference:{timeZone:"UTC",respectsDaylightSaving:false},
    preferredTimeReference:null,types:[],templates:[{name:"Street",description:"",drawingTool:"esriFeatureEditToolLine",prototype:{attributes:{streetwidt:null,borough:null,build_stat:null,cco_st:null,date_edit_:null,time_edit_:null,feat_statu:null,feat_type:null,honorary_n:null,marg_wharf:null,old_st_nm:null,paper_st:null,record_st:null,roadway_ty:null,route_type:null,stair_st:null,street_nm:null}}}],supportedQueryFormats:"JSON, geoJSON, PBF",supportedAppendFormats:"sqlite,geoPackage,shapefile,filegdb,featureCollection,geojson,csv,excel",supportedExportFormats:"csv,shapefile,sqlite,geoPackage,filegdb,featureCollection,geojson,excel",supportedSpatialRelationships:["esriSpatialRelIntersects","esriSpatialRelContains","esriSpatialRelCrosses","esriSpatialRelEnvelopeIntersects","esriSpatialRelIndexIntersects","esriSpatialRelOverlaps","esriSpatialRelTouches","esriSpatialRelWithin","esriSpatialRelDisjoint","esriSpatialRelRelation"],supportedContingentValuesFormats:"JSON, PBF",supportedSyncDataOptions:4,hasStaticData:false,maxRecordCount:1000,standardMaxRecordCount:4000,standardMaxRecordCountNoGeometry:32000,tileMaxRecordCount:4000,maxRecordCountFactor:1,capabilities:"Query,ChangeTracking"};
}
