# iModel.js Extract API Build

trigger: none

schedules:
  - cron: "0 5 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:
    - checkout: self
      clean: true
    - task: NodeTool@0
      displayName: "Use Node 14"
      inputs:
        versionSpec: 14.17.0
        checkLatest: true
    - script: node common/scripts/install-run-rush.js install
      displayName: rush install
      workingDirectory: $(System.DefaultWorkingDirectory)
    - script: node common/scripts/install-run-rush.js build -v -p max
      displayName: rush build
      workingDirectory: $(System.DefaultWorkingDirectory)
    - script: node common/scripts/install-run-rush.js extract-api
      displayName: rush extract-api
      workingDirectory: $(System.DefaultWorkingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: api'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/imodeljs/common/api'
        ArtifactName: api
