# iTwin.js Test CI Build - if you see this in master... delete it

trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    exclude:
      # - "**.md"
      # - "**/*.md"
      # - docs
      - docs/docs_temp.md

pr:
  drafts: false
  branches:
    include:
      - master
      - release/*
  paths:
    exclude:
      # - "**.md"
      # - "**/*.md"
      # - docs
      - docs/docs_temp.md

jobs:
  - job:
    workspace:
      clean: all
    pool:
      name: TestCI
      demands: Agent.OS -equals Windows_NT

    steps:
      - script: |
         echo this is a test
        displayName: Echo Test
