# iTwin.js Test CI Build - if you see this in master... delete it
# common/config/azure-pipelines/jobs/test-ci.yaml

trigger:
  branches:
    include:
      - actions-pipeline-test
      - master
  paths:
    exclude:
      - "**.md"
      - docs/**
      - common/config/azure-pipelines/jobs/**
      - this-is-a-test2.yml
      - .github/workflows/**

pr:
  drafts: true
  branches:
    include:
      - actions-pipeline-test
      - master
  paths:
    exclude:
      - "**.md"
      - docs/**
      - common/config/azure-pipelines/jobs/**
      - this-is-a-test2.yml
      - .github/workflows/**

jobs:
  - job:
    workspace:
      clean: all
    pool:
      name: iModelTechCI
      demands: Agent.OS -equals Windows_NT

    steps:
      - script: |
         echo this is a test
        displayName: Pipeline Echo Test
