/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/

// manually curated section
export function registerTool(t: typeof import("@itwin/core-frontend").Tool): Promise<void>

// BEGIN GENERATED CODE
export {
	ContextRotationId,
	ACSType,
	ACSDisplayOptions,
	CoordSystem,
	LocateAction,
	LocateFilterStatus,
	SnapStatus,
	FlashMode,
	FrontendLoggerCategory,
	SnapMode,
	SnapHeat,
	HitSource,
	HitGeomType,
	HitParentGeomType,
	HitPriority,
	HitDetailType,
	OutputMessageType,
	OutputMessagePriority,
	OutputMessageAlert,
	ActivityMessageEndReason,
	MessageBoxType,
	MessageBoxIconType,
	MessageBoxValue,
	SelectionSetEventType,
	StandardViewId,
	ViewStatus,
	GraphicType,
	UniformType,
	VaryingType,
	TileLoadStatus,
	TileVisibility,
	TileLoadPriority,
	TileBoundingBoxes,
	TileTreeLoadStatus,
	TileGraphicType,
	ClipEventType,
	SelectionMethod,
	SelectionMode,
	SelectionProcessing,
	BeButton,
	CoordinateLockOverrides,
	InputSource,
	CoordSource,
	BeModifierKeys,
	EventHandled,
	ParseAndRunResult,
	KeyinParseError,
	StartOrResume,
	ManipulatorToolEvent,
	ToolAssistanceImage,
	ToolAssistanceInputMethod,
	AccuDrawHintBuilder, // REAL
	BingLocationProvider, // REAL
	LocateResponse, // REAL
	EmphasizeElements, // REAL
	FrustumAnimator, // REAL
	GlobeAnimator, // REAL
	canvasToResizedCanvasWithBars, // REAL
	imageBufferToCanvas, // REAL
	canvasToImageBuffer, // REAL
	getImageSourceMimeType, // REAL
	getImageSourceFormatForMimeType, // REAL
	imageElementFromImageSource, // REAL
	imageElementFromUrl, // REAL
	extractImageSourceDimensions, // REAL
	imageBufferToPngDataUrl, // REAL
	imageBufferToBase64EncodedPng, // REAL
	getCompressedJpegFromCanvas, // REAL
	MarginPercent, // REAL
	Marker, // REAL
	Cluster, // REAL
	NotifyMessageDetails, // REAL
	queryTerrainElevationOffset, // REAL
	ViewRect, // REAL
	FeatureSymbology, // REAL
	GraphicBranch, // REAL
	Pixel, // REAL
	readElementGraphics, // REAL
	BingElevationProvider, // REAL
	EditManipulator, // REAL
	PrimitiveTool, // REAL
	BeButtonEvent, // REAL
	Tool, // REAL
	InteractiveTool, // REAL
	InputCollector, // REAL
	ToolAssistance, // REAL
	ViewTool, // REAL
} from "@itwin/core-frontend";

export type {
	OsmBuildingDisplayOptions,
	HitListHolder,
	FeatureOverrideProvider,
	IModelIdArg,
	FuzzySearchResult,
	FrontendSecurityOptions,
	ToolTipOptions,
	SelectAddEvent,
	SelectRemoveEvent,
	SelectReplaceEvent,
	Animator,
	ViewAnimationOptions,
	GlobalAlignmentOptions,
	OnViewExtentsError,
	MarginOptions,
	ViewChangeOptions,
	ViewCreator2dOptions,
	ViewCreator3dOptions,
	GlobalLocationArea,
	GlobalLocation,
	Decorator,
	SelectedViewportChangedArgs,
	ExtentLimits,
	CanvasDecoration,
	GraphicBranchOptions,
	BatchOptions,
	PickableGraphicOptions,
	GraphicBuilderOptions,
	ViewportGraphicBuilderOptions,
	ComputeChordToleranceArgs,
	CustomGraphicBuilderOptions,
	GraphicPrimitive2d,
	GraphicLineString,
	GraphicLineString2d,
	GraphicPointString,
	GraphicPointString2d,
	GraphicShape,
	GraphicShape2d,
	GraphicArc,
	GraphicArc2d,
	GraphicPath,
	GraphicLoop,
	GraphicPolyface,
	GraphicSolidPrimitive,
	ParticleCollectionBuilderParams,
	ParticleProps,
	ParticleCollectionBuilder,
	TextureCacheOwnership,
	TextureImage,
	CreateTextureArgs,
	CreateTextureFromSourceArgs,
	Uniform,
	UniformContext,
	UniformParams,
	UniformArrayParams,
	ScreenSpaceEffectSource,
	ScreenSpaceEffectBuilderParams,
	ScreenSpaceEffectContext,
	ScreenSpaceEffectBuilder,
	TileTreeDiscloser,
	GpuMemoryLimits,
	TileContent,
	TileDrawArgParams,
	TileParams,
	TileTreeOwner,
	TileTreeParams,
	TileTreeSupplier,
	TiledGraphicsProvider,
	ViewClipEventHandler,
	BeButtonEventProps,
	BeTouchEventProps,
	BeWheelEventProps,
	ParseKeyinError,
	ParsedKeyin,
	ToolAssistanceKeyboardInfo,
	ToolAssistanceInstruction,
	ToolAssistanceSection,
	ToolAssistanceInstructions,
	AccuSnap,
	AuxCoordSystemState,
	AuxCoordSystem2dState,
	AuxCoordSystem3dState,
	AuxCoordSystemSpatialState,
	CategorySelectorState,
	ChangeFlags,
	ContextRealityModelState,
	DisplayStyleState,
	DisplayStyle2dState,
	DisplayStyle3dState,
	DrawingViewState,
	LocateOptions,
	ElementPicker,
	ElementLocateManager,
	EntityState,
	ElementState,
	FlashSettingsOptions,
	FlashSettings,
	HitDetail,
	SnapDetail,
	IntersectDetail,
	HitList,
	IModelConnection,
	NotificationHandler,
	MarkerImage,
	MarkerFillStyle,
	MarkerTextAlign,
	MarkerTextBaseline,
	MarkerSet,
	ModelSelectorState,
	ModelState,
	GeometricModelState,
	GeometricModel2dState,
	GeometricModel3dState,
	SheetModelState,
	SpatialModelState,
	PhysicalModelState,
	SpatialLocationModelState,
	DrawingModelState,
	SectionDrawingModelState,
	ActivityMessageDetails,
	NotificationManager,
	PerModelCategoryVisibility,
	SelectionSetEvent,
	HiliteSet,
	SelectionSet,
	SheetViewState,
	SpatialViewState,
	OrthographicViewState,
	Sprite,
	IconSprites,
	SpriteLocation,
	TentativePoint,
	Tiles,
	ViewCreator2d,
	ViewCreator3d,
	ViewManager,
	ViewPose,
	ViewState,
	ViewState3d,
	ViewState2d,
	ViewingSpace,
	CanvasDecorationList,
	Decorations,
	GraphicBuilder,
	GraphicPrimitive,
	RenderClipVolume,
	RenderGraphic,
	RenderGraphicOwner,
	GraphicList,
	RenderSystem,
	TextureCacheKey,
	TextureOwnership,
	TextureImageSource,
	Scene,
	DisclosedTileTreeSet,
	Tile,
	GpuMemoryLimit,
	TileAdmin,
	TileDrawArgs,
	TileRequest,
	TileRequestChannelStatistics,
	TileRequestChannel,
	TileRequestChannels,
	TileTree,
	TileTreeReference,
	TileUsageMarker,
	EventController,
	ToolType,
	ToolList,
	BeButtonState,
	BeTouchEvent,
	BeWheelEvent,
	ParseKeyinResult,
	ToolAdmin,
	ToolSettings,
	ViewManip,
} from "@itwin/core-frontend";

export {
	BackgroundMapType,
	GlobeMode,
	BriefcaseIdValue,
	SyncMode,
	TypeOfChange,
	ChangesetType,
	BisCodeSpec,
	ColorByName,
	CommonLoggerCategory,
	QueryRowFormat,
	MonochromeMode,
	ECSqlValueType,
	ChangeOpCode,
	ChangedValueState,
	ECSqlSystemProperty,
	SectionType,
	Rank,
	FeatureOverrideType,
	BatchType,
	FontType,
	Npc,
	GeoCoordStatus,
	FillDisplay,
	BackgroundFill,
	GeometryClass,
	GeometrySummaryVerbosity,
	FillFlags,
	HSVConstants,
	ImageBufferFormat,
	ImageSourceFormat,
	LinePixels,
	MassPropertiesOperation,
	TextureMapUnits,
	PlanarClipMaskMode,
	PlanarClipMaskPriority,
	SkyBoxImageType,
	SpatialClassifierInsideDisplay,
	SpatialClassifierOutsideDisplay,
	TerrainHeightOriginMode,
	ThematicGradientMode,
	ThematicGradientColorScheme,
	ThematicDisplayMode,
	TxnAction,
	GridOrientationType,
	RenderMode,
	ElementGeometryOpcode,
	GeometryStreamFlags,
	ColorDef, // REAL
} from "@itwin/core-common";

export type {
	AnalysisStyleDisplacementProps,
	AnalysisStyleThematicProps,
	AnalysisStyleProps,
	BackgroundMapProps,
	DeprecatedBackgroundMapProps,
	LocalBriefcaseProps,
	RequestNewBriefcaseProps,
	CameraProps,
	ChangedElements,
	EntityIdAndClassId,
	ChangedEntities,
	ChangesetIndexAndId,
	ChangesetIdWithIndex,
	ChangesetRange,
	CutStyleProps,
	ClipStyleProps,
	CodeProps,
	QueryLimit,
	QueryQuota,
	BaseReaderOptions,
	QueryOptions,
	ContextRealityModelProps,
	ContextRealityModelsContainer,
	DisplayStyleSubCategoryProps,
	DisplayStyleModelAppearanceProps,
	DisplayStylePlanarClipMaskProps,
	DisplayStyleSettingsProps,
	DisplayStyle3dSettingsProps,
	DisplayStyleProps,
	DisplayStyle3dProps,
	DisplayStyleOverridesOptions,
	DisplayStyleSettingsOptions,
	NavigationValue,
	NavigationBindingValue,
	RelatedElementProps,
	ElementProps,
	GeometricElementProps,
	Placement3dProps,
	Placement2dProps,
	GeometricElement3dProps,
	PhysicalElementProps,
	SectionDrawingProps,
	SectionDrawingLocationProps,
	GeometricElement2dProps,
	GeometryPartProps,
	ViewAttachmentProps,
	SubjectProps,
	SheetProps,
	DefinitionElementProps,
	TypeDefinitionElementProps,
	PhysicalTypeProps,
	InformationPartitionElementProps,
	DisplayStyleLoadProps,
	RenderTimelineLoadProps,
	ElementLoadOptions,
	ElementLoadProps,
	ElementAspectProps,
	ExternalSourceAspectProps,
	ChannelRootAspectProps,
	LineStyleProps,
	CategoryProps,
	SubCategoryProps,
	UrlLinkProps,
	RepositoryLinkProps,
	RenderTimelineProps,
	AppearanceOverrideProps,
	EmphasizeElementsProps,
	EntityProps,
	SourceAndTarget,
	RelationshipProps,
	EntityQueryParams,
	EnvironmentProps,
	FeatureAppearanceProps,
	FeatureAppearanceSource,
	FeatureAppearanceProvider,
	FontMapProps,
	GeometryContainmentRequestProps,
	GeometryContainmentResponseProps,
	GeometrySummaryOptions,
	GeometrySummaryRequestProps,
	GroundPlaneProps,
	EcefLocationProps,
	RootSubjectProps,
	FilePropertyProps,
	ModelIdAndGeometryGuid,
	SolarLightProps,
	AmbientLightProps,
	HemisphereLightsProps,
	FresnelSettingsProps,
	LightSettingsProps,
	Localization,
	MassPropertiesRequestProps,
	MassPropertiesResponseProps,
	TextureMapProps,
	RenderMaterialAssetProps,
	RenderMaterialProps,
	ModelClipGroupProps,
	ElementIdsAndRangesProps,
	ModelGeometryChangesProps,
	ExtantElementGeometryChange,
	DeletedElementGeometryChange,
	ModelGeometryChanges,
	ModelProps,
	ModelLoadProps,
	ModelQueryParams,
	GeometricModelProps,
	GeometricModel2dProps,
	GeometricModel3dProps,
	PlanProjectionSettingsProps,
	PlanarClipMaskProps,
	RgbColorProps,
	SessionProps,
	SkyCubeProps,
	SkyBoxProps,
	SolarShadowSettingsProps,
	SpatialClassifierFlagsProps,
	SpatialClassifierProps,
	SpatialClassifiersContainer,
	TerrainProps,
	TextureProps,
	TextureLoadProps,
	TextureData,
	ThematicGradientSettingsProps,
	ThematicDisplaySensorProps,
	ThematicDisplaySensorSettingsProps,
	ThematicDisplayProps,
	ThumbnailFormatProps,
	ThumbnailProps,
	TileVersionInfo,
	ViewDetailsProps,
	ViewDetails3dProps,
	ViewFlagProps,
	SectionDrawingViewProps,
	ViewStateProps,
	ViewStateLoadProps,
	ModelSelectorProps,
	CategorySelectorProps,
	ViewQueryParams,
	ViewDefinitionProps,
	ViewDefinition3dProps,
	SpatialViewDefinitionProps,
	ViewDefinition2dProps,
	AuxCoordSystemProps,
	AuxCoordSystem2dProps,
	AuxCoordSystem3dProps,
	WhiteOnWhiteReversalProps,
	FunctionalElementProps,
	ViewAttachmentLabelProps,
	CalloutProps,
	Helmert2DWithZOffsetProps,
	AdditionalTransformProps,
	CartographicProps,
	HorizontalCRSExtentProps,
	HorizontalCRSProps,
	VerticalCRSProps,
	GeographicCRSProps,
	ElementGeometryDataEntry,
	XyzRotationProps,
	GeocentricTransformProps,
	PositionalVectorTransformProps,
	GridFileDefinitionProps,
	GridFileTransformProps,
	GeodeticTransformProps,
	GeodeticDatumProps,
	GeodeticEllipsoidProps,
	GeometryAppearanceProps,
	AreaFillProps,
	MaterialProps,
	GeometryPartInstanceProps,
	GeometryStreamHeaderProps,
	GeometryStreamEntryProps,
	TextStringPrimitive,
	ImagePrimitive,
	PartReference,
	BRepPrimitive,
	GeometryPrimitive,
	GeometryStreamIteratorEntry,
	ImageGraphicProps,
	AffineTransformProps,
	ProjectionProps,
	Carto2DDegreesProps,
	TextStringProps,
	RpcActivity,
	GraphicsRequestProps,
	PersistentGraphicsRequestProps,
	JsonGeometryStream,
	FlatBufferGeometryStream,
	DynamicGraphicsRequestProps,
	DynamicGraphicsRequest2dProps,
	DynamicGraphicsRequest3dProps,
	BackgroundMapProviderName,
	PersistentBackgroundMapProps,
	Base64EncodedString,
	BriefcaseId,
	EntityIdAndClassIdIterable,
	ChangesetId,
	ChangesetIndex,
	ChangesetIndexOrId,
	CodeScopeProps,
	ColorDefProps,
	PlacementProps,
	FontId,
	RgbFactorProps,
	Point2dProps,
	ElementGeometryChange,
	SkyBoxImageProps,
	TerrainProviderName,
	TweenCallback,
	UpdateCallback,
	EasingFunction,
	InterpolationFunction,
	ViewFlagsProperties,
	ViewFlagOverrides,
	UnitType,
	GeodeticTransformMethod,
	GridFileFormat,
	GridFileDirection,
	GeometryStreamProps,
	GeometryStreamPrimitive,
	ImageGraphicCornersProps,
	AxisAlignedBox3d,
	AxisAlignedBox3dProps,
	ElementAlignedBox3d,
	ElementAlignedBox2d,
	LocalAlignedBox3d,
	Placement,
	ProjectionMethod,
	HemisphereEnum,
	DanishSystem34Region,
	RemoveFunction,
	ElementGraphicsRequestProps,
} from "@itwin/core-common";

// END GENERATED CODE
