/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/

/* eslint-disable @typescript-eslint/naming-convention */
export class PhillyDataset {

  public static readonly multiItemPoint = {type:"FeatureCollection",id:"public.phillytransportationimprovementproject",title:"public.phillytransportationimprovementproject",description:"public.phillytransportationimprovementproject",numberMatched:5629,numberReturned:5,links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Items",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items?limit=5&f=geojson",rel:"self",type:"application/geo+json"},{href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items?limit=5&f=geojson&offset=5",rel:"next",type:"application/geo+json",title:"Next page"}],features:[{type:"Feature",geometry:{type:"Point",coordinates:[-75.311238833,40.068862363]},id:1,properties:{gid:1,objectid:974619477.0},links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Item",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items/1",rel:"item",type:"application/geo+json"}]},{type:"Feature",geometry:{type:"Point",coordinates:[-75.245507088,40.019866491]},id:2,properties:{gid:2,objectid:974619555.0},links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Item",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items/2",rel:"item",type:"application/geo+json"}]},{type:"Feature",geometry:{type:"Point",coordinates:[-75.129881757,39.990804092]},id:3,properties:{gid:3,objectid:974619997.0},links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Item",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items/3",rel:"item",type:"application/geo+json"}]},{type:"Feature",geometry:{type:"Point",coordinates:[-75.245507088,40.019866491]},id:4,properties:{gid:4,objectid:974623572.0},links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Item",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items/4",rel:"item",type:"application/geo+json"}]},{type:"Feature",geometry:{type:"Point",coordinates:[-74.869829744,40.097060198]},id:5,properties:{gid:5,objectid:974624959.0},links:[{title:"Collection",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject",rel:"collection",type:"application/json"},{title:"Item",href:"http://localhost:8081/collections/public.phillytransportationimprovementproject/items/5",rel:"item",type:"application/geo+json"}]}]};

}

