/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/
import { IndexedPolyface } from "../polyface/Polyface";
import { GeometryCoreTestIO } from "./GeometryCoreTestIO";

// cspell:word rhombicosidodecahedron

/**
 * `ImportedSample` has static methods to create a variety of geometry samples useful in testing.
 * @alpha
 */
export class ImportedSample {
  /**
   * Create a 62-sided regular polyhedron with facets of size 3,4,5.
   * * The following auxiliary data is also present:
   * * * per-facet normals
   * * * per-facet color
   * * * per-sector uv parameters (originally generated by Parasolid)
   */
  public static createPolyhedron62(): IndexedPolyface | undefined {
    return GeometryCoreTestIO.jsonFileToIndexedPolyface("./src/test/data/polyface/rhombicosidodecahedron.imjs");
  }
}
