dir ..\..\..\core\bentley\lib\dist\prod\
dir ..\..\..\core\geometry\lib\dist\prod\
dir ..\..\..\core\common\lib\dist\prod\
dir ..\..\..\core\clients\lib\dist\prod\
dir ..\..\..\core\i18n\lib\dist\prod\
dir ..\..\..\core\quantity\lib\dist\prod\
dir ..\..\..\core\frontend\lib\dist\prod\
dir ..\..\..\ui\core\lib\dist\prod\
dir ..\..\..\ui\components\lib\dist\prod\
dir ..\..\..\ui\ninezone\lib\dist\prod\
dir ..\..\..\ui\framework\lib\dist\prod\
dir ..\..\..\presentation\common\lib\dist\prod\
dir ..\..\..\presentation\components\lib\dist\prod\
dir ..\..\..\presentation\frontend\lib\dist\prod\
