parameters:
- name: variableGroup
- name: artifactName

jobs:
- job: RunAudit
  pool: PRG
  variables:
    - group: ${{ parameters.variableGroup }}
  steps:
  - script: echo $(ShortCode)
  - template: templates/scorecard/audit-tool.yaml@build-pipeline-scripts
    parameters:
      auditToolsPath: $(PrgBuildsPath)\Tools\AuditTools\
      legalReleaseType: Commercial
      projectName: $(ShortCode)
      prgId: $(PrgId)
      rsLogPath: $(PrgBuildsPath)\RSLogs\Azure\$(Build.DefinitionName)\$(Build.BuildId)\
      shortCode: $(ShortCode)
      versionNumber: $(Build.BuildNumber)
      artifactName: ${{ parameters.artifactName }}

- job: Scorecard
  dependsOn:
    - RunAudit
  pool:
    vmImage: "windows-latest"
  variables:
    - group: ${{ parameters.variableGroup }}
  steps:
  - template: templates/scorecard/scorecard-common-validators.yaml@build-pipeline-scripts
    parameters:
      gprId: $(GprId)
      shortCode: $(ShortCode)
      isBackendOrAgent: false
      appInsightsService: $(AppInsightsService)
      octopusProjectId: $(OctopusProjectId)
      sloSqlServerName: $(SloSqlServerName)
      sloSqlDatabaseName: $(SloSqlDatabaseName)
      sloSqlDatabaseCredentials: $(SloSqlDatabaseCredentials)
  - template : ./scorecard-gates.yaml

- job: ScorecardReport
  dependsOn: Scorecard
  condition: succeededOrFailed()
  displayName: "Scorecard Results"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: templates/scorecard/scorecard-report.yaml@build-pipeline-scripts
