# iTwin.js Github Actions Test - if you see this in master... delete it

name: Actions Test

on:
  # workflow_dispatch:
  # pull_request:
  push:
    branches:
      # - master
      # - release/*
      - ignore-building-doc-only-changes
    paths-ignore:
      # - "**.md"
      # - "**/*.md"
      # - docs
      - docs/docs_temp.md

jobs:
  extract-api:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo this is a test